### ISSUE TITLE
Erweitern von "White on Top" auf "Player Perspective"

### ISSUE THREAD

**Issue by BlazingTwist** [BlazingTwist/Clean-Code-Development-Jchess#23]
"White on Top" ist nur für 2 Spieler sinnvoll.
Für mehr Spieler wäre es sinnvoller zu fragen, wessen Spielers Perspektive gezeigt werden soll (z.B. Dropdown im UI)

- Backend:
  - [x] Implement Player Perspective for 2PSquare
  - [x] Implement Player Perspective for 3PHex
- dx
  - [x] Create `BoardUpdateSubscribe.schema.json`
- Frontend
  - [x] Display perspective selection

**Comment by martinmarth** [comment]
Gute Idee.  
Wie stellst du dir das vor, soll die Perspektive während des Spiels, mittels des Dropdowns gewechselt werden?

**Comment by BlazingTwist** [comment]
Die aktuelle Implementierung würde das unterstützen. Habe aber ursprünglich nur soweit gedacht, dass man das zum Spielstart auswählt und es dann für den Browser fest ist.
Technisch hält dich auch nichts davon ab, immer die Perspektive des aktiven Spielers zu zeigen.

Glaube aber, dass Perspektivwechsel während des Spiels eher desorientierend wären?
Am einfachsten ist, nur die aktuelle "white-on-top" checkbox durch einen Dropdown zu erstzen.
